[package]
name = "rustman"
version = "0.2.0"
authors = ["Nbiba Bedis <bedisnbiba@gmail.com>"]
edition = "2018"
readme = "README.md"
description = "Cross platfrom package manager"
repository = "https://github.com/sigmaSd/rustman"
license = "MIT"

[dependencies]
http_req = "0.5.0"
dirs = "2.0.1"
termcolor = "1.0.5"
toml = "0.5.1"
